# CRASH COURSE: How to manage any Python environment

### General Anaconda protocoll
#### New environment
1. If you know what python version you need, always specify it when creating new env (preferred)

! See [here](https://github.com/mihaifalcusan/Notes/blob/b3d6e282abcbf0153fe5c4e643f4ae6fdd46ae95/How%20to%20manage%20python%20envs%20using%20Anaconda/basic_ML_env.yml) for a standard environment .yml file, which you can simply use to create a basic ML environment using "conda env create --file basic_ML_env.yml -n new_env")

#### Extending existing envs
0. **Always** clone your nice and working env using navigator as a backup 
1. Do everything in the conda prompt / navigator
2. For package installations, always use the links on [Anaconda.org](www.anaconda.org)
3. Sometimes, if your conda prompt installation freezes, you cand try installing the same packages in the navigator, and it can give you helpful insights about the versions you need (but it takes longer and you might want to use pipdeptree (See below))
3. If conda does not provide help, install using pip (**BUT** pay attention to the following)

### If using pip in conda env
1. always install in C:/Users/mihai/anaconda3/envs/ENV_NAME/Scripts
2. use the command: **python -m pip install PACKAGE_NAME --no-deps** (python -m uses the correct pip venv)
3. afterwards, manually check all dependencies using the command **pipdeptree** (you might have to install the extension by using **python -m pip install pipdeptree**)
4. manually install all dependencies and specify their versions
5. Constantly check if your programs run as intended
6. Delete your backup / use conda rename to only have one correct env at the end